version: '3.8'
services:
  web:
    build:
      context: flask-app
    ports:
      - "5000:5000" 
    stdin_open: true
    volumes:
      - ./flask-app:/app
    depends_on:
      - es
    networks:
      - es-web-net 

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - es-web-net 

networks:
   es-web-net:     
    